### ISSUE TITLE
Experiments

### ISSUE THREAD

**Issue by pfistfl** [slds-lmu/yahpo_gym#15]
- [ ] Per task performance
- [ ] Benchmark additional algorithms
- [ ] Per task `n_configs`

**Comment by pfistfl** [comment]
Algorithms:
- Anything from `mlr3mbo` (BO-GP on lcbench)?
- DEHB
- Dragonfly / Ray / Optuna
- SMAC-HB?

**Comment by sumny** [comment]
- [ ] probably want some abstract optimizer base classes for full fid/ multi fid with unified api and trajectory representation and all of the optimizers above inherit from these

**Comment by sumny** [comment]
General design of experiments:
focus on multifidelity and/or multicrit/

**Comment by sumny** [comment]
Multi objective: connect https://github.com/automl/multi-obj-baselines/tree/main/baselines
