### ISSUE TITLE
Misspecified range for `momentum` in `lcbench` for paper

### ISSUE THREAD

**Issue by eddiebergman** [slds-lmu/yahpo_gym#48]
Just a note that the `momentum` parameter for the lcbench class of benchmarks says `(0.1, 0.9)` in the paper but the configspace lists that its `(0.1, 0.99)`:

```python
In [7]: b = BenchmarkSet("lcbench", "3945")

In [8]: b
Out[8]: BenchmarkSet(lcbench)

In [9]: b.get_opt_space()
Out[9]: 
Configuration space object:
  Hyperparameters:
    ...
    momentum, Type: UniformFloat, Range: [0.1, 0.99], Default: 0.545
```

![Uploading Screenshot_2022-08-24_08-32-39.jpg…]()

**Comment by pfistfl** [comment]
Closing here, as the current implementation seems correct
