### ISSUE TITLE
News section links to LCBench instead of HPOBench repo

### ISSUE THREAD

**Issue by LGro** [slds-lmu/yahpo_gym#51]
I just noticed what seems to be a small typo in the README, where one of the HPOBench links brings one to https://github.com/automl/LCBench instead of https://github.com/automl/HPOBench/, is this intended?

> yahpo_gym is now integrated into [HPOBench](https://github.com/automl/LCBench)'s development branch!

**Comment by sumny** [comment]
Thanks for catching that mistake! :)
