### ISSUE TITLE
R BenchmarkSet::get_objective seems to ignore seed?

### ISSUE THREAD

**Issue by mb706** [slds-lmu/yahpo_gym#53]
seems to be dangerous to suggest that giving a seed will make experiments reproducible when it is actually ignored

https://github.com/slds-lmu/yahpo_gym/blob/6d5a988dae972884c847b81529c73965421583b4/yahpo_gym_r/R/BenchmarkSet.R#L115-L133

**Comment by pfistfl** [comment]
Should be fixed now
