### ISSUE TITLE
Searchspace inconsistent with domain in R

### ISSUE THREAD

**Issue by mb706** [slds-lmu/yahpo_gym#54]
Not sure whether this should be opened here or in yahpo_data:

[The search space for rbv2_super parameter `aknn.ef_construction`](https://github.com/slds-lmu/yahpo_data/blob/f9b8cd24fd8e7d9cc8fb7372f9640128941255e5/rbv2_super/param_set.R#L29) goes from 2 to 7, `exp()` transformed, but the codomain has [upper limit 403](https://github.com/slds-lmu/yahpo_data/blob/f9b8cd24fd8e7d9cc8fb7372f9640128941255e5/rbv2_super/param_set.R#L98). I guess it should be [1097, as in the configspace.json](https://github.com/slds-lmu/yahpo_data/blob/f9b8cd24fd8e7d9cc8fb7372f9640128941255e5/rbv2_super/config_space.json#L85)?

**Comment by pfistfl** [comment]
This should be solved now, domains go from `[1, 256]` for `ef` to [1, 512]` for `ef_construction`.
