### ISSUE TITLE
[enhancement] Please describe the very first setup in the home

### ISSUE THREAD

**Issue by nabenabe0928** [slds-lmu/yahpo_gym#74]
Thank you for the nice benchmark dataset.
I have a suggestion for the enhancement of the doc.
As it took me a while to run the benchmark at the first point, I would like you to add some information regarding the very first setup.
Specifically, the following information helps:
1. The info about `local_config.init_config` (I had no idea what `Could not load local_config!` meant)
2. [The URL to the benchmark data](https://syncandshare.lrz.de/getlink/fiCMkzqj1bv1LfCUyvZKmLvd/)
3. Minimal codeblock to test whether the setup is done.

Although the introduction to the features of this benchmark is important, I think a better installation guide would prevent users from making a decision to not use the benchmark datasets.
Again, thanks for the nice benchmark datasets!

**Comment by pfistfl** [comment]
Hey @nabenabe0928 

Thanks for the feedback, I will update this once I get around to it!

**Comment by pfistfl** [comment]
1) This is documented here: https://github.com/slds-lmu/yahpo_gym/tree/main/yahpo_gym#setup
2) This is also documented in the README, right above the setup part.
3) I have written a sentence on this in the README as well.
