### ISSUE TITLE
Missing Ref for LCBench

### ISSUE THREAD

**Issue by mlindauer** [slds-lmu/yahpo_gym#75]
Hi,

People start to cite YAHPO for LCBench. As one of the authors of LCBench, I'm of course not happy that you get the citations now. Please be very explicit that people should cite the original ref. As a starting point you should change the README.

Best,
Marius

**Comment by sumny** [comment]
Hi Marius,

I am sorry to hear that.
It is definitively not our intention to  'steal' citations from the original LCBench benchmark/dataset.

We updated information regarding data sources of benchmark scenarios and prior work for every README (e.g., https://github.com/slds-lmu/yahpo_gym/tree/main/yahpo_gym) and also the official documentation (https://slds-lmu.github.io/yahpo_gym/scenarios.html). 
Moreover, initializing a benchmark scenario with a citeable data source will now remind users to also cite the original work, e.g.:
```python
from yahpo_gym import benchmark_set
import yahpo_gym.benchmarks.lcbench
bench = benchmark_set.BenchmarkSet("lcbench")
```

will print:

```
Please make sure to also cite:
Zimmer, L., Lindauer, M., & Hutter, F. (2021). Auto-Pytorch: Multi-Fidelity Metalearning for Efficient and Robust AutoDL. IEEE Transactions on Pattern Analysis and Machine Intelligence, 43(9), 3079-3090.
Zimmer, L. (2020). data_2k_lw.zip. figshare. Dataset. https://doi.org/10.6084/m9.figshare.11662422.v1, Apache License, Version 2.0.
```

I hope this satisfies your concerns.

Best,
Lennart
